"""Add imge column to comapny table

Revision ID: 3a02e95825b5
Revises: 0171ecb653f9
Create Date: 2023-08-21 16:52:26.741132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a02e95825b5"
down_revision = "0171ecb653f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image", sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.drop_column("image")

    # ### end Alembic commands ###
